---
abstract: unknown
author:
  - 'Tim Bunce <Tim.Bunce@pobox.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geo-StreetAddress-US
no_index:
  directory:
    - t
    - inc
requires:
  Class::Data::Inheritable: 0.04
version: 1.04
